name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and test frontend
        run: yarn build

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.4"

      - name: Test backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: coverage

      - name: Build backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll
